import Head from "next/head";

interface PropsTypes {
  title?: string;
}

//
const PageHead = (props: PropsTypes) => {
  return (
    <Head>
      <title>{props.title}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

// export
export default PageHead;
